version: '3.12'

services:
  web:
    build: ./web
    # wait for db, then migrate, then start
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do 
          echo '...still waiting' &&
          sleep 1;
        done && 
        echo 'Database up - running migrations' &&
        python manage.py migrate && 
        echo 'Starting Django' &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./web:/code
    ports:
      - "8001:8000"
    env_file:
      - web/.env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kcc-data
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
