# Generated by Django 5.2.3 on 2025-06-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='FAO-NRM Data Portal', max_length=100, verbose_name='Site title')),
                ('header_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Header color')),
                ('footer_color', models.CharField(default='#5792c9', max_length=7, verbose_name='Footer color')),
                ('card_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Card background')),
                ('body_bg_color', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Body background')),
                ('body_text_color', models.CharField(default='#5792c9', max_length=7, verbose_name='Body text color')),
                ('organization', models.CharField(default='FAO-NRM Data Portal', max_length=100, verbose_name='Organization name')),
                ('copyright_year', models.PositiveIntegerField(default=2025, verbose_name='Copyright year')),
            ],
            options={
                'verbose_name': 'Portal setting',
                'verbose_name_plural': 'Portal settings',
            },
        ),
        migrations.CreateModel(
            name='PortalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Card title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(verbose_name='Link URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='portal.portalsetting')),
            ],
            options={
                'verbose_name': 'Portal card',
                'verbose_name_plural': 'Portal cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='portal.portalsetting')),
            ],
            options={
                'verbose_name': 'Carousel image',
                'verbose_name_plural': 'Carousel images',
                'ordering': ['order'],
            },
        ),
    ]
