# Generated by Django 5.2.3 on 2025-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a 16x16 or 32x32 .ico or .png favicon', upload_to='favicons/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='footer_text_color',
            field=models.CharField(default='#080808', max_length=7, verbose_name='Footer text color'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='header_text_color',
            field=models.CharField(default='#080808', max_length=7, verbose_name='Header text color'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='login_text_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Login link color'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a square or landscape logo (e.g. 100x100px or 200x50px)', upload_to='logos/', verbose_name='Logo'),
        ),
    ]
