# Generated by Django 5.2.3 on 2025-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_portalsetting_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='HTML or plain text for the About page', verbose_name='About content')),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About pages',
            },
        ),
    ]
