# Generated by Django 5.2.3 on 2025-06-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content_ar',
            field=models.TextField(help_text='HTML or plain text for the About page', null=True, verbose_name='About content'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='content_en',
            field=models.TextField(help_text='HTML or plain text for the About page', null=True, verbose_name='About content'),
        ),
        migrations.AddField(
            model_name='portalcard',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portalcard',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='portalcard',
            name='title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Card title'),
        ),
        migrations.AddField(
            model_name='portalcard',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Card title'),
        ),
    ]
