# Generated by Django 5.2.3 on 2025-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_aboutpage_content_ar_aboutpage_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsetting',
            name='organization_ar',
            field=models.CharField(default='FAO-NRM Data Portal', max_length=100, null=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='organization_en',
            field=models.CharField(default='FAO-NRM Data Portal', max_length=100, null=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='site_title_ar',
            field=models.CharField(default='FAO-NRM Data Portal', max_length=100, null=True, verbose_name='Site title'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='site_title_en',
            field=models.CharField(default='FAO-NRM Data Portal', max_length=100, null=True, verbose_name='Site title'),
        ),
    ]
