# Generated by Django 5.2.3 on 2025-07-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_portalsetting_home_label_portalsetting_main_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalsetting',
            name='main_label',
        ),
    ]
