# Generated by Django 5.2.3 on 2025-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_portalsetting_main_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsetting',
            name='home_label_ar',
            field=models.CharField(default='Home', help_text='Label for the Home nav link', max_length=30, null=True, verbose_name='Home link text'),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='home_label_en',
            field=models.CharField(default='Home', help_text='Label for the Home nav link', max_length=30, null=True, verbose_name='Home link text'),
        ),
    ]
