# Generated by Django 5.2.5 on 2025-09-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_portalsetting_home_label_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalsetting',
            name='home_label_ar',
        ),
        migrations.RemoveField(
            model_name='portalsetting',
            name='home_label_en',
        ),
    ]
