# Generated by Django 5.2.3 on 2025-07-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_thematic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalthematicsetting',
            name='home_label',
            field=models.CharField(default='Home', help_text='Label for the Home nav link', max_length=30, verbose_name='Home link text'),
        ),
        migrations.AddField(
            model_name='portalthematicsetting',
            name='main_label',
            field=models.CharField(default='Main', help_text='Label for the Main-site nav link (back to the central portal)', max_length=30, verbose_name='Main site link text'),
        ),
    ]
