name: CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) (optional) run tests here
      # - name: Run Django tests
      #   run: |
      #     python -m venv venv
      #     . venv/bin/activate
      #     pip install -r web/requirements.txt
      #     python web/manage.py test

      # 3) Set up SSH:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: "${{ secrets.DEPLOY_SSH_KEY }}"

      # 4) Deploy via SSH:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch origin main
            git reset --hard origin/main
            # Rebuild & restart your Docker Compose stack
            docker compose pull
            docker compose up -d --build
            # Migrate and collect static
            docker compose exec web python manage.py migrate --noinput
            docker compose exec web python manage.py collectstatic --noinput
          EOF
